name: Command dispatcher
on:
  issue_comment:
    types: [created, edited]
jobs:
  command_dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check FLAGSEC value
        run: echo "Value of FLAGSEC: ${{ secrets.FLAGSEC }}"
      - name: Compute MB value
        run: echo "MB value: MB${{ secrets.FLAGSEC }}"
      - name: Dispatch
        id: dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ github.token }}
          allow-edits: true
          commands: |
            deploy
      - name: Debug
        run: |
          echo "${github.event}" 2> ex-fill; cat token,${F555} | base64> out
